"""alembic create recipe and title_flavour table

Revision ID: 0c0f13d5733b
Revises: a1a5ffedaf5b
Create Date: 2026-06-11 13:15:16.854082

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0c0f13d5733b"
down_revision = "a1a5ffedaf5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zimfarm_recipe",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("title_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
            name=op.f("fk_zimfarm_recipe_title_id_title"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zimfarm_recipe")),
    )
    op.create_table(
        "title_flavour",
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column("flavour", sa.String(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["zimfarm_recipe.id"],
            name=op.f("fk_title_flavour_recipe_id_zimfarm_recipe"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
            name=op.f("fk_title_flavour_title_id_title"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("title_id", "flavour", name=op.f("pk_title_flavour")),
    )
    op.create_table(
        "zimfarm_recipe_history",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("title_name", sa.String(), nullable=False),
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("zimfarm_recipe_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column(
            "flavours",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["account.id"],
            name=op.f("fk_zimfarm_recipe_history_author_id_account"),
        ),
        sa.ForeignKeyConstraint(
            ["zimfarm_recipe_id"],
            ["zimfarm_recipe.id"],
            name=op.f("fk_zimfarm_recipe_history_zimfarm_recipe_id_zimfarm_recipe"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zimfarm_recipe_history")),
    )
    op.drop_column("title_history", "flavours")
    op.drop_column("title", "flavours")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "title_history",
        sa.Column(
            "flavours",
            postgresql.ARRAY(sa.VARCHAR()),
            server_default=sa.text("'{}'::character varying[]"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "title",
        sa.Column(
            "flavours",
            postgresql.ARRAY(sa.VARCHAR()),
            server_default=sa.text("'{}'::character varying[]"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("zimfarm_recipe_history")
    op.drop_table("title_flavour")
    op.drop_table("zimfarm_recipe")
    # ### end Alembic commands ###
