"""add zimcheck_s3_deleted to book

Revision ID: 13c0e15bcd02
Revises: e4935745168d
Create Date: 2026-06-23 08:40:35.605091

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13c0e15bcd02"
down_revision = "e4935745168d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book",
        sa.Column(
            "zimcheck_s3_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.create_index(
        "idx_book_zimcheck_s3_deleted",
        "book",
        ["zimcheck_s3_deleted"],
        unique=False,
        postgresql_where=sa.text("zimcheck_s3_deleted = FALSE"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "zimcheck_s3_deleted")
    op.drop_index(
        "idx_book_zimcheck_s3_deleted",
        table_name="book",
        postgresql_where=sa.text("zimcheck_s3_deleted = FALSE"),
    )
    # ### end Alembic commands ###
