"""store illustraion hashes

Revision ID: 148e2b179499
Revises: 13c0e15bcd02
Create Date: 2026-06-25 14:22:54.491838

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "148e2b179499"
down_revision = "13c0e15bcd02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book", sa.Column("illustration_48x48_at_1_hash", sa.String(), nullable=True)
    )
    op.add_column(
        "title", sa.Column("illustration_48x48_at_1_hash", sa.String(), nullable=True)
    )
    op.add_column(
        "title_history",
        sa.Column("illustration_48x48_at_1_hash", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("title_history", "illustration_48x48_at_1_hash")
    op.drop_column("title", "illustration_48x48_at_1_hash")
    op.drop_column("book", "illustration_48x48_at_1_hash")
    # ### end Alembic commands ###
