"""make warehouse name unique

Revision ID: 1625ae981cfb
Revises: 7c36d46dd0dd
Create Date: 2026-05-05 14:26:31.772973

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1625ae981cfb"
down_revision = "7c36d46dd0dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_warehouse_name"), "warehouse", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_warehouse_name"), table_name="warehouse")
    # ### end Alembic commands ###
