"""set up database models

Revision ID: 222139c5c331
Revises:
Create Date: 2026-02-12 16:05:17.118056

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "222139c5c331"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("media_count", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column(
            "zimcheck_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "zim_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("flavour", sa.String(), nullable=True),
        sa.Column(
            "needs_processing", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("has_error", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "needs_file_operation", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "location_kind", sa.String(), server_default="quarantine", nullable=False
        ),
        sa.Column("deletion_date", sa.DateTime(), nullable=True),
        sa.Column("events", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("title_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
            name=op.f("fk_book_title_id_title"),
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
    )
    op.create_index(
        "idx_book_has_error",
        "book",
        ["has_error"],
        unique=False,
        postgresql_where=sa.text("has_error = TRUE"),
    )
    op.create_index(
        "idx_book_location_kind_quarantine",
        "book",
        ["location_kind"],
        unique=False,
        postgresql_where=sa.text("location_kind = 'quarantine'"),
    )
    op.create_index(
        "idx_book_location_kind_staging",
        "book",
        ["location_kind"],
        unique=False,
        postgresql_where=sa.text("location_kind = 'staging'"),
    )
    op.create_index(
        "idx_book_needs_file_operation",
        "book",
        ["needs_file_operation"],
        unique=False,
        postgresql_where=sa.text("needs_file_operation = TRUE"),
    )
    op.create_index(
        "idx_book_needs_processing",
        "book",
        ["needs_processing"],
        unique=False,
        postgresql_where=sa.text("needs_processing = TRUE"),
    )
    op.create_table(
        "title",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("maturity", sa.String(), nullable=False),
        sa.Column("events", postgresql.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_title")),
    )
    op.create_index(op.f("ix_title_maturity"), "title", ["maturity"], unique=False)
    op.create_index(op.f("ix_title_name"), "title", ["name"], unique=True)
    op.create_table(
        "user",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("idp_sub", sa.Uuid(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column(
            "deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "warehouse",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouse")),
    )
    op.create_table(
        "book_location",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["book.id"], name=op.f("fk_book_location_book_id_book")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_book_location_warehouse_id_warehouse"),
        ),
        sa.PrimaryKeyConstraint(
            "book_id", "warehouse_id", "path", "status", name=op.f("pk_book_location")
        ),
    )
    op.create_table(
        "collection",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("download_base_url", sa.String(), nullable=True),
        sa.Column("view_base_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_collection_warehouse_id_warehouse"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection")),
    )
    op.create_index(op.f("ix_collection_name"), "collection", ["name"], unique=True)
    op.create_table(
        "refresh_token",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "token",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("expire_time", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_refresh_token_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
    )
    op.create_table(
        "zimfarm_notification",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("events", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"], ["book.id"], name=op.f("fk_zimfarm_notification_book_id_book")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zimfarm_notification")),
    )
    op.create_index(
        "idx_zimfarm_notification_status_bad_notification",
        "zimfarm_notification",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'bad_notification'"),
    )
    op.create_index(
        "idx_zimfarm_notification_status_pending",
        "zimfarm_notification",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "collection_title",
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_collection_title_collection_id_collection"),
        ),
        sa.ForeignKeyConstraint(
            ["title_id"], ["title.id"], name=op.f("fk_collection_title_title_id_title")
        ),
        sa.PrimaryKeyConstraint(
            "title_id", "collection_id", name=op.f("pk_collection_title")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_title")
    op.drop_index(
        "idx_zimfarm_notification_status_pending",
        table_name="zimfarm_notification",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "idx_zimfarm_notification_status_bad_notification",
        table_name="zimfarm_notification",
        postgresql_where=sa.text("status = 'bad_notification'"),
    )
    op.drop_table("zimfarm_notification")
    op.drop_table("refresh_token")
    op.drop_index(op.f("ix_collection_name"), table_name="collection")
    op.drop_table("collection")
    op.drop_table("book_location")
    op.drop_table("warehouse")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_title_name"), table_name="title")
    op.drop_index(op.f("ix_title_maturity"), table_name="title")
    op.drop_table("title")
    op.drop_index(
        "idx_book_needs_processing",
        table_name="book",
        postgresql_where=sa.text("needs_processing = TRUE"),
    )
    op.drop_index(
        "idx_book_needs_file_operation",
        table_name="book",
        postgresql_where=sa.text("needs_file_operation = TRUE"),
    )
    op.drop_index(
        "idx_book_location_kind_staging",
        table_name="book",
        postgresql_where=sa.text("location_kind = 'staging'"),
    )
    op.drop_index(
        "idx_book_location_kind_quarantine",
        table_name="book",
        postgresql_where=sa.text("location_kind = 'quarantine'"),
    )
    op.drop_index(
        "idx_book_has_error",
        table_name="book",
        postgresql_where=sa.text("has_error = TRUE"),
    )
    op.drop_table("book")
    # ### end Alembic commands ###
