"""add increase/decrease thresholds for media/article count

Revision ID: 275477bbacde
Revises: 13c0e15bcd02
Create Date: 2026-07-01 15:41:58.027116

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "275477bbacde"
down_revision = "13c0e15bcd02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column("article_count_increase_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "collection",
        sa.Column("media_count_increase_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "collection",
        sa.Column("article_count_decrease_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "collection",
        sa.Column("media_count_decrease_threshold", sa.Float(), nullable=True),
    )
    op.execute(
        """
        UPDATE collection
        SET article_count_increase_threshold = article_count_change_threshold,
            article_count_decrease_threshold = article_count_change_threshold
        WHERE
            article_count_change_threshold IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE collection
        SET media_count_increase_threshold = media_count_change_threshold,
            media_count_decrease_threshold = media_count_change_threshold
        WHERE
            media_count_change_threshold IS NOT NULL
        """
    )
    op.drop_column("collection", "article_count_change_threshold")
    op.drop_column("collection", "media_count_change_threshold")

    op.add_column(
        "collection_history",
        sa.Column("article_count_increase_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "collection_history",
        sa.Column("media_count_increase_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "collection_history",
        sa.Column("article_count_decrease_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "collection_history",
        sa.Column("media_count_decrease_threshold", sa.Float(), nullable=True),
    )
    op.execute(
        """
        UPDATE collection_history
        SET article_count_increase_threshold = article_count_change_threshold,
            article_count_decrease_threshold = article_count_change_threshold
        WHERE
            article_count_change_threshold IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE collection_history
        SET media_count_increase_threshold = media_count_change_threshold,
            media_count_decrease_threshold = media_count_change_threshold
        WHERE
            media_count_change_threshold IS NOT NULL
        """
    )
    op.drop_column("collection_history", "article_count_change_threshold")
    op.drop_column("collection_history", "media_count_change_threshold")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection_history",
        sa.Column(
            "media_count_change_threshold",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.execute(
        """
        UPDATE collection_history
        SET media_count_change_threshold = COALESCE(
                media_count_decrease_threshold,
                media_count_increase_threshold
        )
        WHERE
            media_count_decrease_threshold IS NOT NULL
            OR media_count_increase_threshold IS NOT NULL
        """
    )
    op.add_column(
        "collection_history",
        sa.Column(
            "article_count_change_threshold",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.execute(
        """
        UPDATE collection_history
        SET article_count_change_threshold = COALESCE(
                article_count_decrease_threshold,
                article_count_increase_threshold
        )
        WHERE
            article_count_decrease_threshold IS NOT NULL
            OR article_count_increase_threshold IS NOT NULL
        """
    )
    op.drop_column("collection_history", "media_count_decrease_threshold")
    op.drop_column("collection_history", "article_count_decrease_threshold")
    op.drop_column("collection_history", "media_count_increase_threshold")
    op.drop_column("collection_history", "article_count_increase_threshold")
    op.add_column(
        "collection",
        sa.Column(
            "media_count_change_threshold",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.execute(
        """
        UPDATE collection
        SET media_count_change_threshold = COALESCE(
                media_count_decrease_threshold,
                media_count_increase_threshold
        )
        WHERE
            media_count_decrease_threshold IS NOT NULL
            OR media_count_increase_threshold IS NOT NULL
        """
    )
    op.add_column(
        "collection",
        sa.Column(
            "article_count_change_threshold",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.execute(
        """
        UPDATE collection
        SET article_count_change_threshold = COALESCE(
                article_count_decrease_threshold,
                article_count_increase_threshold
        )
        WHERE
            article_count_decrease_threshold IS NOT NULL
            OR article_count_increase_threshold IS NOT NULL
        """
    )
    op.drop_column("collection", "media_count_decrease_threshold")
    op.drop_column("collection", "article_count_decrease_threshold")
    op.drop_column("collection", "media_count_increase_threshold")
    op.drop_column("collection", "article_count_increase_threshold")
    # ### end Alembic commands ###
