"""add-log-entries

Revision ID: 2c699e7d3dd4
Revises: 8b190eda9c41
Create Date: 2022-10-04 16:10:24.649133

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c699e7d3dd4"
down_revision = "8b190eda9c41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("object_id", sa.String(length=100), nullable=False),
        sa.Column("object_repr", sa.String(length=255), nullable=False),
        sa.Column("action", sa.Integer(), nullable=False),
        sa.Column("action_time", sa.DateTime(), nullable=True),
        sa.Column("user", sa.String(length=100), nullable=True),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("log_entries")
    # ### end Alembic commands ###
