"""create book title foreign key

Revision ID: 323cd3ac0fdf
Revises: 9b1940316bba
Create Date: 2026-02-17 08:27:01.638502

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "323cd3ac0fdf"
down_revision = "9b1940316bba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_book_title_id_title"), "book", "title", ["title_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_book_title_id_title"), "book", type_="foreignkey")
    # ### end Alembic commands ###
