"""add task_id to zimfarm_notification

Revision ID: 3f1e2ff013ed
Revises: f2eb6aa14ba9
Create Date: 2026-09-10 14:31:13.978259

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f1e2ff013ed"
down_revision = "f2eb6aa14ba9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "zimfarm_notification",
        sa.Column(
            "task_id",
            sa.Uuid(),
            nullable=False,
            # setting server default to this UUID instead of text(gen_random_uuid())
            # so that we can identify old notifications that didn't come with a task
            # ID
            server_default="00000000-0000-0000-0000-000000000000",
        ),
    )
    op.drop_constraint(
        "pk_zimfarm_notification", "zimfarm_notification", type_="primary"
    )

    op.create_primary_key(
        "pk_zimfarm_notification",
        "zimfarm_notification",
        ["id", "task_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "pk_zimfarm_notification", "zimfarm_notification", type_="primary"
    )
    op.create_primary_key(
        "pk_zimfarm_notification",
        "zimfarm_notification",
        ["id", "task_id"],
    )
    op.drop_column("zimfarm_notification", "task_id")
    # ### end Alembic commands ###
