"""add last_book_added_at to title flavour

Revision ID: 3f26951f6100
Revises: 75f0c4e0f8af
Create Date: 2026-07-20 09:40:22.035542

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f26951f6100"
down_revision = "75f0c4e0f8af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "title_flavour",
        sa.Column(
            "last_book_added_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("title_flavour", "last_book_added_at")
    # ### end Alembic commands ###
