"""Use alter

Revision ID: 40b58eace3fb
Revises: a37d94d59b8b
Create Date: 2025-10-24 09:38:03.364905

"""

# revision identifiers, used by Alembic.
revision = "40b58eace3fb"
down_revision = "a37d94d59b8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
