"""initial schema

Revision ID: 5376af219730
Revises:
Create Date: 2025-12-19 16:29:46.586314

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5376af219730"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("media_count", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column(
            "zimcheck_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "zim_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("flavour", sa.String(), nullable=True),
        sa.Column(
            "status", sa.String(), server_default="pending_processing", nullable=False
        ),
        sa.Column("events", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("title_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
            name=op.f("fk_book_title_id_title"),
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
    )
    op.create_index(
        "idx_book_status_bad_book",
        "book",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'bad_book'"),
    )
    op.create_index(
        "idx_book_status_errored",
        "book",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'errored'"),
    )
    op.create_index(
        "idx_book_status_pending_move",
        "book",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending_move'"),
    )
    op.create_index(
        "idx_book_status_pending_processing",
        "book",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending_processing'"),
    )
    op.create_index(
        "idx_book_status_pending_title",
        "book",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending_title'"),
    )
    op.create_table(
        "title",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("maturity", sa.String(), nullable=False),
        sa.Column("events", postgresql.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_title")),
    )
    op.create_index(op.f("ix_title_maturity"), "title", ["maturity"], unique=False)
    op.create_index(op.f("ix_title_name"), "title", ["name"], unique=True)
    op.create_table(
        "warehouse",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouse")),
    )
    op.create_table(
        "book_location",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["book.id"], name=op.f("fk_book_location_book_id_book")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_book_location_warehouse_id_warehouse"),
        ),
        sa.PrimaryKeyConstraint(
            "book_id", "warehouse_id", "path", "status", name=op.f("pk_book_location")
        ),
    )
    op.create_table(
        "collection",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouse.id"],
            name=op.f("fk_collection_warehouse_id_warehouse"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection")),
    )
    op.create_index(op.f("ix_collection_name"), "collection", ["name"], unique=True)
    op.create_table(
        "zimfarm_notification",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("events", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"], ["book.id"], name=op.f("fk_zimfarm_notification_book_id_book")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zimfarm_notification")),
    )
    op.create_index(
        "idx_zimfarm_notification_status_bad_notification",
        "zimfarm_notification",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'bad_notification'"),
    )
    op.create_index(
        "idx_zimfarm_notification_status_pending",
        "zimfarm_notification",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "collection_title",
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_collection_title_collection_id_collection"),
        ),
        sa.ForeignKeyConstraint(
            ["title_id"], ["title.id"], name=op.f("fk_collection_title_title_id_title")
        ),
        sa.PrimaryKeyConstraint(
            "title_id", "collection_id", name=op.f("pk_collection_title")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_title")
    op.drop_index(
        "idx_zimfarm_notification_status_pending",
        table_name="zimfarm_notification",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "idx_zimfarm_notification_status_bad_notification",
        table_name="zimfarm_notification",
        postgresql_where=sa.text("status = 'bad_notification'"),
    )
    op.drop_table("zimfarm_notification")
    op.drop_index(op.f("ix_collection_name"), table_name="collection")
    op.drop_table("collection")
    op.drop_table("book_location")
    op.drop_table("warehouse")
    op.drop_index(op.f("ix_title_name"), table_name="title")
    op.drop_index(op.f("ix_title_maturity"), table_name="title")
    op.drop_table("title")
    op.drop_index(
        "idx_book_status_pending_title",
        table_name="book",
        postgresql_where=sa.text("status = 'pending_title'"),
    )
    op.drop_index(
        "idx_book_status_pending_processing",
        table_name="book",
        postgresql_where=sa.text("status = 'pending_processing'"),
    )
    op.drop_index(
        "idx_book_status_pending_move",
        table_name="book",
        postgresql_where=sa.text("status = 'pending_move'"),
    )
    op.drop_index(
        "idx_book_status_errored",
        table_name="book",
        postgresql_where=sa.text("status = 'errored'"),
    )
    op.drop_index(
        "idx_book_status_bad_book",
        table_name="book",
        postgresql_where=sa.text("status = 'bad_book'"),
    )
    op.drop_table("book")
    # ### end Alembic commands ###
