"""add filename to book

Revision ID: 56433a685cf7
Revises: f85a39c29683
Create Date: 2026-06-12 08:38:28.149382

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "56433a685cf7"
down_revision = "f85a39c29683"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("filename", sa.String(), nullable=True))
    op.execute(
        """
        UPDATE book
        SET filename = book_location.filename
        FROM book_location
        WHERE book.id = book_location.book_id
        AND book_location.status = 'current'
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "filename")
    # ### end Alembic commands ###
