"""add retain_old_books to collection

Revision ID: 6a3021320d3d
Revises: 3f1e2ff013ed
Create Date: 2026-09-17 10:11:01.624481

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6a3021320d3d"
down_revision = "3f1e2ff013ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column(
            "retain_old_books", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "collection_history",
        sa.Column(
            "retain_old_books", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "retain_old_books")
    op.drop_column("collection_history", "retain_old_books")
    # ### end Alembic commands ###
