"""Add support for flavors

Revision ID: 6c6181d36517
Revises: 40b58eace3fb
Create Date: 2025-10-24 14:29:19.514445

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c6181d36517"
down_revision = "40b58eace3fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_title_last_book_id_book", "title", type_="foreignkey")
    op.drop_column("title", "last_book_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "title",
        sa.Column("last_book_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "fk_title_last_book_id_book", "title", "book", ["last_book_id"], ["id"]
    )
    # ### end Alembic commands ###
