"""create_title_flavour_table

Revision ID: 75f0c4e0f8af
Revises: f8d05e886704
Create Date: 2026-07-09 09:16:33.538108

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "75f0c4e0f8af"
down_revision = "f8d05e886704"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "title_flavour",
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column("flavour", sa.String(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
            name=op.f("fk_title_flavour_title_id_title"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("title_id", "flavour", name=op.f("pk_title_flavour")),
    )
    op.add_column("book", sa.Column("recipe_id", sa.Uuid(), nullable=True))
    op.execute(
        """
        INSERT INTO title_flavour (title_id, flavour, recipe_id)
        SELECT id, unnest(flavours), NULL
        FROM title
        """
    )
    op.drop_column("title", "flavours")
    op.execute("ALTER TABLE title_history ALTER COLUMN flavours TYPE text")
    op.execute(
        """
        UPDATE title_history
        SET flavours = COALESCE(
            (
                SELECT jsonb_agg(
                    jsonb_build_object('flavour', elem, 'recipe_id', NULL)
                )::text
                FROM unnest(flavours::text[]) AS t(elem)
            ),
            '[]'
        )
        """
    )
    op.execute("ALTER TABLE title_history ALTER COLUMN flavours DROP DEFAULT")
    op.execute(
        "ALTER TABLE title_history ALTER COLUMN flavours TYPE jsonb "
        "USING flavours::jsonb"
    )
    op.alter_column(
        "title_history",
        "flavours",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        nullable=False,
        existing_server_default=sa.text("'{}'::character varying[]"),
        server_default=sa.text("'{}'::jsonb"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("title_flavour")
    op.drop_column("book", "recipe_id")
    op.add_column(
        "title",
        sa.Column(
            "flavours",
            postgresql.ARRAY(sa.VARCHAR()),
            server_default=sa.text("'{}'::character varying[]"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.execute("ALTER TABLE title_history ALTER COLUMN flavours TYPE text")
    op.execute(
        """
        UPDATE title_history
        SET flavours = COALESCE(
            (
                SELECT array_agg(rec.f ->> 'flavour')::text
                FROM jsonb_array_elements(flavours::jsonb) AS rec(f)
            ),
            '{}'
        )
        """
    )
    op.execute("ALTER TABLE title_history ALTER COLUMN flavours DROP DEFAULT")
    op.execute(
        "ALTER TABLE title_history ALTER COLUMN flavours TYPE character varying[] "
        "USING flavours::character varying[]"
    )
    op.alter_column(
        "title_history",
        "flavours",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
        server_default=sa.text("'{}'::character varying[]"),
    )
    # ### end Alembic commands ###
