"""added-titletags

Revision ID: 7739aed017eb
Revises: 23a35bf09895
Create Date: 2021-12-15 00:50:21.763857

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7739aed017eb"
down_revision = "23a35bf09895"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "titles_titletags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titletag", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["title"],
            ["titles.ident"],
            name="fk_titles_titletags_titles_title_ident",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["titletag"],
            ["titles_tags.name"],
            name="fk_titles_titletags_titles_tags_titletag_name",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("titles_booktags")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "titles_booktags",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("booktag", sa.VARCHAR(length=255), nullable=True),
        sa.Column("title", sa.VARCHAR(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["booktag"],
            ["books_tags.name"],
            name="fk_titles_booktags_books_tags_booktag_name",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title"],
            ["titles.ident"],
            name="fk_titles_booktags_titles_title_ident",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("titles_titletags")
    # ### end Alembic commands ###
