"""add display_name field for accounts

Revision ID: 7c36d46dd0dd
Revises: 8f0ee48f7dce
Create Date: 2026-04-30 09:01:39.497891

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = "7c36d46dd0dd"
down_revision = "8f0ee48f7dce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    # First, make the display_name column nullable and populate with entries
    # the column table (which was previously non-nullable)
    op.add_column("account", sa.Column("display_name", sa.String(), nullable=True))
    session.execute(
        sa.text(
            """
            UPDATE "account"
            SET display_name = "account".username
            """
        )
    )
    op.alter_column("account", "username", existing_type=sa.VARCHAR(), nullable=True)
    # Set the display_name column to be non-nullable
    op.alter_column("account", "display_name", existing_type=sa.VARCHAR, nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("account", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("account", "display_name")
    # ### end Alembic commands ###
