"""create collection history

Revision ID: 8cd022c48b90
Revises: ba65df9ffbf3
Create Date: 2026-06-02 15:39:18.478200

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8cd022c48b90"
down_revision = "ba65df9ffbf3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_history",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("download_base_url", sa.String(), nullable=True),
        sa.Column("view_base_url", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["account.id"],
            name=op.f("fk_collection_history_author_id_account"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_collection_history_collection_id_collection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_history")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_history")
    # ### end Alembic commands ###
