"""rename user to account

Revision ID: 8f0ee48f7dce
Revises: eb212a007a90
Create Date: 2026-04-29 11:55:20.724507

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8f0ee48f7dce"
down_revision = "eb212a007a90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all indices on the user table
    op.drop_index("ix_user_username", table_name="user")
    # Drop constraints and rename columns against other tables
    op.drop_constraint(
        "fk_refresh_token_user_id_user", "refresh_token", type_="foreignkey"
    )
    # Rename the table from user to account and recreate the indices
    op.rename_table("user", "account")
    # Rename the primary key constraint to match the new table name
    op.execute("ALTER TABLE account RENAME CONSTRAINT pk_user TO pk_account")
    op.create_index(op.f("ix_account_idp_sub"), "account", ["idp_sub"], unique=True)
    op.create_index(op.f("ix_account_username"), "account", ["username"], unique=True)

    op.alter_column("refresh_token", "user_id", new_column_name="account_id")
    op.create_index(
        "ix_refresh_token_account_id_token",
        table_name="refresh_token",
        columns=["account_id", "token"],
        unique=True,
    )

    # Recreate the inbound foreign key constraints to account
    op.create_foreign_key(
        op.f("fk_refresh_token_account_id_account"),
        "refresh_token",
        "account",
        ["account_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all foreign keys pointing to account table
    op.drop_constraint(
        op.f("fk_refresh_token_account_id_account"),
        "refresh_token",
        type_="foreignkey",
    )
    op.drop_index("ix_refresh_token_account_id_token", table_name="refresh_token")
    op.drop_index(op.f("ix_account_username"), table_name="account")
    op.drop_index(op.f("ix_account_idp_sub"), table_name="account")

    op.execute("ALTER TABLE account RENAME CONSTRAINT pk_account TO pk_user")
    op.rename_table("account", "user")
    # Recreate foreign keys to user table
    op.alter_column("refresh_token", "account_id", new_column_name="user_id")
    op.create_foreign_key(
        "fk_refresh_token_user_id_user",
        "refresh_token",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_index("ix_user_username", "user", ["username"], unique=True)
    # ### end Alembic commands ###
