"""title name is unique

Revision ID: 92d03596d8f7
Revises: add_producer_fields
Create Date: 2025-11-07 14:25:11.815803

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "92d03596d8f7"
down_revision = "add_producer_fields"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_book_status_pending_notification",
        table_name="book",
        postgresql_where="((status)::text = 'pending_notification'::text)",
    )
    op.create_index(
        "idx_book_status_pending_processing",
        "book",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending_processing'"),
    )
    op.create_index(op.f("ix_title_name"), "title", ["name"], unique=True)
    op.drop_index(
        "ix_zimfarm_notification_status_pending_bad",
        table_name="zimfarm_notification",
        postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, "
        "'bad_notification'::character varying])::text[]))",
    )
    op.create_index(
        "idx_zimfarm_notification_status_bad_notification",
        "zimfarm_notification",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'bad_notification'"),
    )
    op.create_index(
        "idx_zimfarm_notification_status_pending",
        "zimfarm_notification",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_zimfarm_notification_status_pending",
        table_name="zimfarm_notification",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "idx_zimfarm_notification_status_bad_notification",
        table_name="zimfarm_notification",
        postgresql_where=sa.text("status = 'bad_notification'"),
    )
    op.create_index(
        "ix_zimfarm_notification_status_pending_bad",
        "zimfarm_notification",
        ["status"],
        unique=False,
        postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, "
        "'bad_notification'::character varying])::text[]))",
    )
    op.drop_index(op.f("ix_title_name"), table_name="title")
    op.drop_index(
        "idx_book_status_pending_processing",
        table_name="book",
        postgresql_where=sa.text("status = 'pending_processing'"),
    )
    op.create_index(
        "idx_book_status_pending_notification",
        "book",
        ["status"],
        unique=False,
        postgresql_where="((status)::text = 'pending_notification'::text)",
    )
    # ### end Alembic commands ###
