"""create title history

Revision ID: 932875a3e13a
Revises: 9dc25bcae26f
Create Date: 2026-05-28 08:41:45.354317

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = "932875a3e13a"
down_revision = "9dc25bcae26f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        sa.text(
            """
            INSERT INTO "account"
                (username, display_name, role, password_hash, deleted, idp_sub)
            VALUES ('maint-scripts', 'maint-scripts', 'viewer', NULL, FALSE, NULL)
            ON CONFLICT (username) DO NOTHING
            """
        ),
    )
    op.create_table(
        "title_history",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("creator", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("illustration_48x48_at_1", sa.String(), nullable=True),
        sa.Column("long_description", sa.String(), nullable=True),
        sa.Column("license", sa.String(), nullable=True),
        sa.Column("relation", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("maturity", sa.String(), nullable=False),
        sa.Column(
            "collection_titles",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "flavours",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["account.id"],
            name=op.f("fk_title_history_author_id_account"),
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
            name=op.f("fk_title_history_title_id_title"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_title_history")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("title_history")
    # ### end Alembic commands ###
