"""add flavours to title

Revision ID: 9dc25bcae26f
Revises: a8f64135b053
Create Date: 2026-05-26 12:24:41.086893

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9dc25bcae26f"
down_revision = "e70e0c595eb9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "title",
        sa.Column(
            "flavours",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("title", "flavours")
    # ### end Alembic commands ###
