"""add item and media count change threshold to collection

Revision ID: a1a5ffedaf5b
Revises: f85a39c29683
Create Date: 2026-06-09 14:38:43.090018

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1a5ffedaf5b"
down_revision = "56433a685cf7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column("article_count_change_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "collection",
        sa.Column("media_count_change_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "collection_history",
        sa.Column("article_count_change_threshold", sa.Float(), nullable=True),
    )
    op.add_column(
        "collection_history",
        sa.Column("media_count_change_threshold", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "media_count_change_threshold")
    op.drop_column("collection", "article_count_change_threshold")
    op.drop_column("collection_history", "media_count_change_threshold")
    op.drop_column("collection_history", "article_count_change_threshold")
    # ### end Alembic commands ###
