"""Add more columns

Revision ID: a37d94d59b8b
Revises: e7b49a8907c1
Create Date: 2025-10-24 09:36:18.311092

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a37d94d59b8b"
down_revision = "e7b49a8907c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book", sa.Column("events", postgresql.ARRAY(sa.String()), nullable=False)
    )
    op.add_column(
        "title", sa.Column("events", postgresql.ARRAY(sa.String()), nullable=False)
    )
    op.add_column(
        "zimfarm_notification",
        sa.Column("events", postgresql.ARRAY(sa.String()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("zimfarm_notification", "events")
    op.drop_column("title", "events")
    op.drop_column("book", "events")
    # ### end Alembic commands ###
