"""add download stats table

Revision ID: a4b2365eb87c
Revises: b7f1c2a4d9e3
Create Date: 2026-10-06 12:46:54.645423

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a4b2365eb87c"
down_revision = "b7f1c2a4d9e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_stats_fetch",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column(
            "fetched_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("nb_downloads", sa.BigInteger(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("day", name=op.f("pk_download_stats_fetch")),
    )
    op.create_table(
        "download_stats",
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column("flavour", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "lb_downloads",
            postgresql.ARRAY(sa.Integer()),
            server_default=sa.text("array_fill(NULL::integer, ARRAY[366])"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "array_length(lb_downloads, 1) = 366",
            name=op.f("ck_download_stats_lb_downloads_length"),
        ),
        sa.ForeignKeyConstraint(
            ["title_id", "flavour"],
            ["title_flavour.title_id", "title_flavour.flavour"],
            name=op.f("fk_download_stats_title_id_title_flavour"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "title_id", "flavour", "year", name=op.f("pk_download_stats")
        ),
    )
    op.create_index(
        op.f("ix_download_stats_year"), "download_stats", ["year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_download_stats_year"), table_name="download_stats")
    op.drop_table("download_stats")
    op.drop_table("download_stats_fetch")
    # ### end Alembic commands ###
