"""add deletion_date to book

Revision ID: a5f67b148119
Revises: df6a64dec5a0
Create Date: 2026-02-09 13:41:08.318866

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5f67b148119"
down_revision = "df6a64dec5a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("deletion_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "deletion_date")
    # ### end Alembic commands ###
