"""change viewer roles to public viewer

Revision ID: a9e085bba147
Revises: 6a3021320d3d
Create Date: 2026-09-22 10:03:49.479372

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a9e085bba147"
down_revision = "6a3021320d3d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE account
        SET role = 'public-viewer'
        WHERE role = 'viewer'
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE account
        SET role = 'viewer'
        WHERE role IN ('public-viewer', 'global-viewer')
    """)
    # ### end Alembic commands ###
