"""allow collections to be private

Revision ID: ab56192a5aa9
Revises: ccdd284d7bb0
Create Date: 2026-07-22 13:20:09.790157

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab56192a5aa9"
down_revision = "ccdd284d7bb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column("is_private", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "collection_history",
        sa.Column("is_private", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "is_private")
    op.drop_column("collection_history", "is_private")
    # ### end Alembic commands ###
