"""add title uploader permission

Revision ID: b7f1c2a4d9e3
Revises: d191892b681d
Create Date: 2026-10-05 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7f1c2a4d9e3"
down_revision = "d191892b681d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "title_permission",
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_title_permission_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["title.id"],
            name=op.f("fk_title_permission_title_id_title"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "title_id", "account_id", name=op.f("pk_title_permission")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("title_permission")
    # ### end Alembic commands ###
