"""create book history

Revision ID: ba65df9ffbf3
Revises: 932875a3e13a
Create Date: 2026-06-01 10:29:39.275297

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = "ba65df9ffbf3"
down_revision = "932875a3e13a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        sa.text(
            """
            INSERT INTO "account"
                (username, display_name, role, password_hash, deleted, idp_sub)
            VALUES ('maint-scripts', 'maint-scripts', 'viewer', NULL, FALSE, NULL)
            ON CONFLICT (username) DO NOTHING
            """
        ),
    )
    op.create_table(
        "book_history",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("flavour", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["account.id"],
            name=op.f("fk_book_history_author_id_account"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
            name=op.f("fk_book_history_book_id_book"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_history")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_history")
    # ### end Alembic commands ###
