"""add collection editor permission

Revision ID: ccdd284d7bb0
Revises: 3f26951f6100
Create Date: 2026-07-21 11:18:27.097542

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ccdd284d7bb0"
down_revision = "3f26951f6100"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_permission",
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_collection_permission_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
            name=op.f("fk_collection_permission_collection_id_collection"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "collection_id", "account_id", name=op.f("pk_collection_permission")
        ),
    )
    op.execute(
        """
        UPDATE account
        SET role = 'global-editor'
        WHERE role = 'editor'
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_permission")
    op.execute(
        """
        UPDATE account
        SET role = 'editor'
        WHERE role = 'global-editor'
        """
    )
    # ### end Alembic commands ###
