"""make s3_key for title uploads nullable

Revision ID: d191892b681d
Revises: a9e085bba147
Create Date: 2026-09-25 09:50:58.527974

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d191892b681d"
down_revision = "a9e085bba147"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("title_upload", "s3_key", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "title_upload", "s3_key", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
