"""Revamp database

Revision ID: e1a0680e37f0
Revises:
Create Date: 2025-10-20 11:46:02.437545

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e1a0680e37f0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("media_count", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column(
            "zimcheck_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "zim_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("title_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["title_id"], ["title.id"], name=op.f("fk_book_title_id_title")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
    )
    op.create_table(
        "title",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("last_book_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_book_id"], ["book.id"], name=op.f("fk_title_last_book_id_book")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_title")),
    )
    op.create_table(
        "zim_store",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zim_store")),
    )
    op.create_table(
        "book_copy",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("created", sa.Boolean(), nullable=False),
        sa.Column(
            "deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("zim_store_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["book.id"], name=op.f("fk_book_copy_book_id_book")
        ),
        sa.ForeignKeyConstraint(
            ["zim_store_id"],
            ["zim_store.id"],
            name=op.f("fk_book_copy_zim_store_id_zim_store"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_copy")),
    )
    op.create_index(
        "idx_book_copy_created_true",
        "book_copy",
        ["created"],
        unique=False,
        postgresql_where=sa.text("created IS true"),
    )
    op.create_index(
        "idx_book_copy_deleted_true",
        "book_copy",
        ["deleted"],
        unique=False,
        postgresql_where=sa.text("deleted IS true"),
    )
    op.create_table(
        "zimfarm_notification",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "processed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"], ["book.id"], name=op.f("fk_zimfarm_notification_book_id_book")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zimfarm_notification")),
    )
    op.create_index(
        "idx_zimfarm_notification_processed_false",
        "zimfarm_notification",
        ["processed"],
        unique=False,
        postgresql_where=sa.text("processed IS false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_zimfarm_notification_processed_false",
        table_name="zimfarm_notification",
        postgresql_where=sa.text("processed IS false"),
    )
    op.drop_table("zimfarm_notification")
    op.drop_index(
        "idx_book_copy_deleted_true",
        table_name="book_copy",
        postgresql_where=sa.text("deleted IS true"),
    )
    op.drop_index(
        "idx_book_copy_created_true",
        table_name="book_copy",
        postgresql_where=sa.text("created IS true"),
    )
    op.drop_table("book_copy")
    op.drop_table("zim_store")
    op.drop_table("title")
    op.drop_table("book")
    # ### end Alembic commands ###
