"""add zimcheck_summary to book

Revision ID: e4935745168d
Revises: a1a5ffedaf5b
Create Date: 2026-06-18 10:50:52.175303

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e4935745168d"
down_revision = "a1a5ffedaf5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book",
        sa.Column(
            "zimcheck_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "zimcheck_summary")
    # ### end Alembic commands ###
