"""add metadata to title

Revision ID: e70e0c595eb9
Revises: a8f64135b053
Create Date: 2026-05-25 08:20:45.716452

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e70e0c595eb9"
down_revision = "a8f64135b053"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("title", sa.Column("title", sa.String(), nullable=True))
    op.add_column("title", sa.Column("creator", sa.String(), nullable=True))
    op.add_column("title", sa.Column("publisher", sa.String(), nullable=True))
    op.add_column("title", sa.Column("description", sa.String(), nullable=True))
    op.add_column("title", sa.Column("language", sa.String(), nullable=True))
    op.add_column(
        "title", sa.Column("illustration_48x48_at_1", sa.String(), nullable=True)
    )
    op.add_column("title", sa.Column("long_description", sa.String(), nullable=True))
    op.add_column("title", sa.Column("license", sa.String(), nullable=True))
    op.add_column("title", sa.Column("relation", sa.String(), nullable=True))
    op.add_column("title", sa.Column("source", sa.String(), nullable=True))
    op.add_column(
        "book",
        sa.Column(
            "issues",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("title", "source")
    op.drop_column("title", "relation")
    op.drop_column("title", "license")
    op.drop_column("title", "long_description")
    op.drop_column("title", "illustration_48x48_at_1")
    op.drop_column("title", "language")
    op.drop_column("title", "description")
    op.drop_column("title", "publisher")
    op.drop_column("title", "creator")
    op.drop_column("title", "title")
    op.drop_column("book", "issues")
    # ### end Alembic commands ###
