"""Initial database schema

Revision ID: e7b49a8907c1
Revises:
Create Date: 2025-10-23 13:59:04.894412

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e7b49a8907c1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("media_count", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column(
            "zimcheck_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "zim_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("title_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
    )
    op.create_table(
        "title",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("last_book_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_book_id"], ["book.id"], name=op.f("fk_title_last_book_id_book")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_title")),
    )
    op.create_foreign_key(
        "fk_book_title_id_title", "book", "title", ["title_id"], ["id"]
    )
    op.create_table(
        "zimfarm_notification",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "processed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "errored", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"], ["book.id"], name=op.f("fk_zimfarm_notification_book_id_book")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zimfarm_notification")),
    )
    op.create_index(
        "idx_zimfarm_notification_errored_false",
        "zimfarm_notification",
        ["errored"],
        unique=False,
        postgresql_where=sa.text("errored IS true"),
    )
    op.create_index(
        "idx_zimfarm_notification_processed_false",
        "zimfarm_notification",
        ["processed"],
        unique=False,
        postgresql_where=sa.text("processed IS false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_zimfarm_notification_processed_false",
        table_name="zimfarm_notification",
        postgresql_where=sa.text("processed IS false"),
    )
    op.drop_index(
        "idx_zimfarm_notification_errored_false",
        table_name="zimfarm_notification",
        postgresql_where=sa.text("errored IS true"),
    )
    op.drop_table("zimfarm_notification")
    op.drop_table("title")
    op.drop_table("book")
    # ### end Alembic commands ###
