"""add updated_at to books

Revision ID: eb212a007a90
Revises: eefbc005d243
Create Date: 2026-04-28 13:38:24.552996

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb212a007a90"
down_revision = "eefbc005d243"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "updated_at")
    # ### end Alembic commands ###
