"""add local user details

Revision ID: f133e17aa945
Revises: a5f67b148119
Create Date: 2026-02-10 11:35:10.652021

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f133e17aa945"
down_revision = "a5f67b148119"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
    )
    op.add_column("user", sa.Column("password_hash", sa.String(), nullable=True))
    op.drop_constraint(op.f("pk_user"), "user", type_="primary")
    op.alter_column("user", "idp_sub", existing_type=sa.UUID(), nullable=True)
    op.create_primary_key(op.f("pk_user"), "user", ["id"])

    op.create_table(
        "refresh_token",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "token",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("expire_time", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_refresh_token_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "idp_sub", existing_type=sa.UUID(), nullable=False)
    op.drop_column("user", "password_hash")
    # op.drop_column("user", "id") uncommented as this should be the pk regardless
    op.drop_table("refresh_token")
    # ### end Alembic commands ###
