"""add book_id to title_upload

Revision ID: f2eb6aa14ba9
Revises: 5ea3bcb33c00
Create Date: 2026-09-04 09:15:26.536119

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f2eb6aa14ba9"
down_revision = "5ea3bcb33c00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("title_upload", sa.Column("book_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_title_upload_book_id_book"),
        "title_upload",
        "book",
        ["book_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_title_upload_book_id_book"), "title_upload", type_="foreignkey"
    )
    op.drop_column("title_upload", "book_id")
    # ### end Alembic commands ###
