"""backup book locations

Revision ID: f85a39c29683
Revises: 9e3e097d4b1b
Create Date: 2026-06-05 13:11:35.514754

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f85a39c29683"
down_revision = "8cd022c48b90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_location",
        sa.Column(
            "is_backup", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_location", "is_backup")
    # ### end Alembic commands ###
