"""make flavours non-nullable

Revision ID: f8d05e886704
Revises: 275477bbacde
Create Date: 2026-07-07 12:11:11.711263

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f8d05e886704"
down_revision = "275477bbacde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE book
        SET flavour = ''
        WHERE flavour IS NULL
        """
    )
    op.execute(
        """
        UPDATE book_history
        SET flavour = ''
        WHERE flavour IS NULL
        """
    )
    op.alter_column("book", "flavour", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "book_history", "flavour", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("book", "flavour", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "book_history", "flavour", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
