"""remove obsolete field from Book

Revision ID: 9254dad0c9f0
Revises: 7739aed017eb
Create Date: 2021-12-20 16:48:55.095499

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9254dad0c9f0"
down_revision = "7739aed017eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "obsolete")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("obsolete", sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
