<template>
  <div>
    <div>
      <table class="table table-hover">
        <tbody v-if="book_id">
          <tr>
            <td>Id</td>
            <td>{{ book_id }}</td>
          </tr>
          <tr>
            <td>Article Count</td>
            <td>{{ book_article_count }}</td>
          </tr>
          <tr>
            <td>Media Count</td>
            <td>{{ book_media_count }}</td>
          </tr>
          <tr>
            <td>Counter</td>
            <td>{{ book_counter }}</td>
          </tr>
          <tr>
            <td>Metadata</td>
            <td>{{ book_metadata }}</td>
          </tr>
          <tr>
            <td>Period</td>
            <td>{{ book_period }}</td>
          </tr>
          <tr>
            <td>Size</td>
            <td>{{ book_size }}</td>
          </tr>
          <tr>
            <td>Url</td>
            <td>{{ book_url }}</td>
          </tr>
          <tr>
            <td>Zimcheck</td>
            <td>{{ book_zimcheck }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <ErrorMessage
      v-if="error"
      :message="error"
    />
  </div>
</template>

<script>
import Common from '../Common.mixin.js'
import ErrorMessage from '../components/ErrorMessage.vue'

export default {
  name: 'BookDetails',
  components: {
    ErrorMessage
  },
  mixins: [Common],
  props: {
    id: {
      type: String,
      default: null
    }
  },
  data () {
    return {
      book_id: null,
      book_article_count: null,
      book_media_count: null,
      book_counter: null,
      book_metadata: null,
      book_period: null,
      book_size: null,
      book_url: null,
      book_zimcheck: null,
      error: null // error message generated by API
    }
  },
  created () {
    const parent = this
    this.startLoading()

    const url = `/books/${this.id}`

    this.queryAPI('GET', url)
      .then(function (response) {
        parent.book_id = response.data.id
        parent.book_article_count = response.data.article_count
        parent.book_media_count = response.data.media_count
        parent.book_counter = response.data.counter
        parent.book_metadata = response.data.metadata
        parent.book_period = response.data.period
        parent.book_size = response.data.size
        parent.book_url = response.data.url
        parent.book_zimcheck = response.data.zimcheck
        parent.endLoading()
      })
      .catch(function (error) {
        parent.standardErrorHandling(error)
        parent.endLoading()
      })
  }

}
</script>
