<template>
  <div class="container">
    <table
      v-if="digesters"
      class="table"
    >
      <thead>
        <tr>
          <th>Digesters</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="digester in digesters"
          :key="digester.slug"
        >
          <td>
            {{ digester.slug }}
          </td>
          <td>{{ digester.description }}</td>
          <td>
            <a
              class="btn btn-secondary btn-sm"
              target="_blank"
              :href="getLink (digester.slug)"
            >
              generate {{ digester.slug }}
            </a>
          </td>
          <td>
            <a
              class="btn btn-secondary btn-sm"
              target="_blank"
              :href="getXmlFile (digester.slug)"
            >
              get {{ digester.slug }}
            </a>
          </td>
        </tr>
      </tbody>
    </table>
    <ErrorMessage
      v-if="error"
      :message="error"
    />
  </div>
</template>

<script>
import Constants from '../constants.js'
import Common from '../Common.mixin.js'
import ErrorMessage from '../components/ErrorMessage.vue'

export default {
  name: 'DigestersListing',
  components: {
    ErrorMessage
  },
  mixins: [Common],
  data () {
    return {
      digesters: null,
      error: null // error message generated by API
    }
  },
  created () {
    const parent = this
    this.startLoading()

    const url = '/digesters'

    this.queryAPI('GET', url)
      .then(function (response) {
        parent.digesters = response.data.items
        parent.endLoading()
      })
      .catch(function (error) {
        parent.standardErrorHandling(error)
        parent.endLoading()
      })
  },
  methods: {
    getLink (slug) {
      return `${Constants.backend_api}/digesters/${slug}/trigger`
    },
    getXmlFile (slug) {
      return `${Constants.backend_api}/digesters/${slug}/library.xml`
    }
  }
}
</script>
