<template>
  <div class="container">
    <table
      class="table table-sm table-striped table-responsive"
    >
      <thead>
        <tr>
          <th>ZimCheck Dashboard</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Total book</td>
          <td>Total check passing</td>
          <td>Total check not passing</td>
        </tr>
        <td>
          {{ totalBook }}
        </td>
        <td>30</td>
        <td>39</td>
      </tbody>
    </table>
    <ErrorMessage
      v-if="error"
      :message="error"
    />
  </div>
</template>

<script>
import Common from '../Common.mixin.js'
import ErrorMessage from '../components/ErrorMessage.vue'

export default {
  name: 'ZimcheckDashboard',
  components: {
    ErrorMessage
  },
  mixins: [Common],
  data () {
    return {
      totalBook: null,
      error: null // error message generated by API
    }
  },
  created () {
    const parent = this
    this.startLoading()

    const url = '/dashboard'

    this.queryAPI('GET', url)
      .then(function (response) {
        parent.totalBook = response.data.totalBook
        parent.endLoading()
      })
      .catch(function (error) {
        parent.standardErrorHandling(error)
        parent.endLoading()
      })
  }
}
</script>
