<template>
  <div class="container">
    <h2>ZimCheck Dashboard</h2>
    <div class="container">
      <div class="row">
        <div
          v-for="value in checkTotals"
          id="hide"
          :key="value"
          class="col btn btn-light position-relative me-1"
        >
          {{ value[0] }}
          <hr>
          <span
            class="badge"
            :class="isError(value[0]) ? 'bg-danger': 'bg-warning'"
          >
            {{ value[1] }}
          </span>
        </div>
      </div>
    </div>
    <hr>
    <table
      class="table table-sm table-striped table-responsive"
    >
      <thead>
        <tr>
          <th>Scraper</th>
          <th
            v-for="value in checkTotals"
            id="hide"
            :key="value"
          >
            {{ value[0] }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="(checks, scraper) in scraperData"
          id="hide"
          :key="scraper"
        >
          <th>
            {{ scraper }}
          </th>
          <td
            v-for="value in checkTotals"
            id="hide"
            :key="value"
          >
            <span
              v-if="value[1] === 0"
            >
              -
            </span>
            <span
              v-else-if="!checks[value[0]]"
            >
              0 %
            </span>
            <span
              v-else
            >
              {{ Math.round((checks[value[0]] * 100) / value[1]) }} %
            </span>
          </td>
        </tr>
      </tbody>
    </table>
    <ErrorMessage
      v-if="error"
      :message="error"
    />
  </div>
</template>

<script>
import Common from '../Common.mixin.js'
import ErrorMessage from '../components/ErrorMessage.vue'

export default {
  name: 'ZimcheckDashboard',
  components: {
    ErrorMessage
  },
  mixins: [Common],
  data () {
    return {
      scraperData: null,
      checkTotals: null,
      knownChecks: null,
      error: null // error message generated by API
    }
  },
  created () {
    const parent = this
    this.startLoading()

    const url = '/zimcheck'

    this.queryAPI('GET', url)
      .then(function (response) {
        // list of known check we want to display values for (can be extended)
        const knownChecks = new Map([
          ['checksum', 'error'],
          ['integrity', 'error'],
          ['empty', 'error'],
          ['metadata', 'error'],
          ['favicon', 'error'],
          ['main_page', 'error'],
          ['redundant', 'warning'],
          ['url_internal', 'error'],
          ['url_external', 'error'],
          ['redirect', 'error']
        ])

        parent.checkTotals = new Map()

        knownChecks.forEach((value, key) => parent.checkTotals.set(key, 0))
        parent.knownChecks = knownChecks
        parent.scraperData = response.data.checkData
        for (const data of Object.values(parent.scraperData)) {
          for (const [check, value] of Object.entries(data)) {
            parent.checkTotals.set(check, (parent.checkTotals.get(check) || 0) + value)
          }
        }
      })
      .catch(function (error) {
        parent.standardErrorHandling(error)
      })
      .finally(function () {
        parent.endLoading()
      })
  },
  methods: {
    isError (check) {
      if (this.knownChecks.get(check) === 'error') {
        return true
      } else {
        return false
      }
    }
  }
}
</script>
