name: Tests

on: [push, pull_request]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  tests-coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: x64

      - name: Run tests
        run: |
          pip install -U pip invoke setuptools==65.5.0 toml==0.10.2
          cd backend
          invoke install-deps --package test
          invoke test --args "-v"
          pwd
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          directory: backend/src
